name: 'put elephone in to fridge'
on: [push, pull_request]
jobs:
  prepareEle:   # first job
    runs-on: ubuntu-latest
    steps:
      - name: go to zoo
        run: "echo 'find elephant in the zoo'"
      - name: get ele
        run: "echo 'elephant is ready'"
        
  prepareFridge: # second job
    runs-on: ubuntu-latest
    steps:
      - name: buy fridge
        run: "echo 'go to buy fridge'"
      - name: standing by
        run: "echo 'fridge is on power, temperature is cool'"
  
  putEleIn: #thirid job
    runs-on: ubuntu-latest
    steps:
      - name: open the fridge
        run: "echo 'fridge is open'"
      - name: put ele in
        run: "echo 'ele  in'"
      - name: close the door
        run: "echo 'door close, finish!'"
